set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {leds_0[0]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {leds_0[1]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {leds_0[2]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {leds_0[3]}]

set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[15]_i_3_n_0}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[31]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[15]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[28]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[23]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[25]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[16]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[27]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[20]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[8]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[21]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[14]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[23]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[18]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[13]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[12]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[27]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[30]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[10]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[29]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[17]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[29]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[8]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[31]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[12]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[24]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[24]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[17]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[10]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[19]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[13]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[26]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[22]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[26]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[16]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[22]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[11]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[15]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[30]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[11]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[15]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[19]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[28]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[18]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[25]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[21]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[31]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[14]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[20]}]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[7]}]

set_property HD.RECONFIGURABLE true [get_cells design_1_wrapper/design_1_i/partial_led_test_v1_0_0/inst/partial_led_test_v1_0_S00_AXI_inst]

set_property HD.RECONFIGURABLE true [get_cells design_1_wrapper/design_1_i/partial_led_0]
create_pblock pblock_partial_led_0
add_cells_to_pblock [get_pblocks pblock_partial_led_0] [get_cells -quiet [list design_1_wrapper/design_1_i/partial_led_0]]
resize_pblock [get_pblocks pblock_partial_led_0] -add {SLICE_X54Y71:SLICE_X67Y97}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_partial_led_0]
set_property SNAPPING_MODE ON [get_pblocks pblock_partial_led_0]
