set_property SRC_FILE_INFO {cfile:/home/alex/GitHub/ZyEthCAP/nicap_extend/.Xil/Vivado-9859-alex-warc/dcp19/axis_dwidth_converter_0_in_context.xdc rfile:../dcp19/axis_dwidth_converter_0_in_context.xdc id:1 order:EARLY scoped_inst:present/input_axis} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alex/GitHub/ZyEthCAP/nicap_extend/.Xil/Vivado-9859-alex-warc/dcp20/axis_dwidth_converter_1_in_context.xdc rfile:../dcp20/axis_dwidth_converter_1_in_context.xdc id:2 order:EARLY scoped_inst:present/output_axis} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins present/input_axis/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells present/input_axis]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins present/output_axis/aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells present/output_axis]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells present/input_axis]
