# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == partial_led_test_v1_0_S00_AXI || REF_NAME == partial_led_test_v1_0_S00_AXI}]
