webtalk_init -webtalk_dir /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.tmp/present_v1_0_project/present_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/present_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 28 15:47:36 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174217199_1777515649_210675447_365" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "95b09816-8671-49e8-9b95-f89843a90ed9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "98cf0f29e3324de08517c1024c921c13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3061.806 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "18" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "186 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "28 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "466" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "65" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "228292_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2995416665 -regid "174217199_1777515649_210675447_365" -xml /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.tmp/present_v1_0_project/present_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/present_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.tmp/present_v1_0_project/present_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/present_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.tmp/present_v1_0_project/present_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/present_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
