# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-16481-alex-pc/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/e2dd/hdl/verilog
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/hdl
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_1/hdl
  } {
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/synth/bd_afc3_s00a2s_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/synth/bd_afc3_m00s2a_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/synth/bd_afc3_m00e_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/synth/bd_afc3_sarn_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/synth/bd_afc3_srn_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/synth/bd_afc3_s00mmu_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/synth/bd_afc3_s00tr_0.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/synth/bd_afc3_s00sic_0.sv
      /tools/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/e2dd/hdl/verilog
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/hdl
    /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_1/hdl
  } {
      ./.Xil/Vivado-16481-alex-pc/realtime/bit_buffer_fifo_stub.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/synth/design_1_processing_system7_0_2.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/ipshared/a6fe/verilog/icap_ctrl.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_icap_ctrl_0_1/synth/zycap_icap_ctrl_0_1.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/7714/src/zycap.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/synth/design_1_zycap_0_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_xlconcat_0_0/synth/design_1_xlconcat_0_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/synth/bd_afc3.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/synth/bd_afc3_one_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/synth/design_1_axi_smc_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/synth/design_1_xbar_1.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/synth/design_1_xbar_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/synth/design_1.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/hdl/axis_infrastructure_v1_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/hdl/axis_register_slice_v1_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/hdl/axis_dwidth_converter_v1_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_0/synth/axis_dwidth_converter_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/ip/axis_dwidth_converter_1/synth/axis_dwidth_converter_1.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/hdl/aes_v1_0_S00_AXI.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/hdl/aes_v1_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/new/top.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/synth/aes_v1_0_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/2c8d/sources_1/new/crypto_top.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/synth/design_1_crypto_top_0_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/synth/design_1_auto_pc_3.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/synth/design_1_auto_pc_4.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/synth/design_1_auto_pc_1.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/synth/design_1_auto_pc_0.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/synth/design_1_auto_pc_2.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/enet_bridge.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/framePassThru.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/framedecrementer.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/new/framedecrementer_wrap.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/frameincrementer.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/frameincrementer_wrap.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/rx_arb.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/imports/src/tx_arb.v
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/imports/nicap_extend/sources_1/imports/sources_1/new/sys_top.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/ip/blk_mem_gen_0/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/ip/blk_mem_gen_0/synth/blk_mem_gen_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/ip/fifo_generator_1/synth/fifo_generator_1.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/ip/fifo_generator_0/synth/fifo_generator_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/synth/design_1_blk_mem_gen_0_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/synth/design_1_blk_mem_gen_0_1.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/synth/design_1_axi_bram_ctrl_0_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/synth/design_1_axi_bram_ctrl_0_1.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/synth/design_1_rst_processing_system7_0_50M_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_2_0/synth/design_1_axi_bram_ctrl_2_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_3_0/synth/design_1_axi_bram_ctrl_3_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/synth/bd_afc3_psr_aclk_0.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/synth/design_1_axi_dma_0_1.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/types.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/cipher_cu.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/math.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/sbox.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/state_reg.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/cipher.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/counter.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/encryption_module.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/inv_cipher_cu.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/inv_cipher.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/decrementor.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/decryption_module.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/key_expander.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/dp_ram.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/key_expansion_cu.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/key_expansion.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/aes_module_cu.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/aes_module.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_crypto_top_0_0/sources_1/ip/aes_v1_0_0/sources_1/imports/aes_1.0/src/aes_wrapper.vhd
    }
      rt::read_vhdl -lib fifo_generator_v13_2_1 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/ip/fifo_generator_1/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_bram_ctrl_v4_0_13 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/20fd/hdl/axi_bram_ctrl_v4_0_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/2751/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_12 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_10 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_17 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_8 /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_16 {
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/hdl/axi_dma_v7_1_vh_rfs.vhd
      /home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_zycap_0_0/src/zycap_axi_dma_0_0/synth/zycap_axi_dma_0_0.vhd
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-16481-alex-pc/realtime/sys_top_synth.xdc
    rt::sdcChecksum
    set rt::top sys_top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/alex/GitHub/ZyEthCAP/nicap_extend/nicap_test.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-16481-alex-pc/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
