# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alex/GitHub/zynq-ip-cores/aes_1.0/src/axis_dwidth_converter_1_1/axis_dwidth_converter_1.xci
# IP: The module: 'axis_dwidth_converter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/GitHub/zynq-ip-cores/aes_1.0/src/axis_dwidth_converter_1_1/axis_dwidth_converter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/alex/GitHub/zynq-ip-cores/aes_1.0/src/axis_dwidth_converter_1_1/axis_dwidth_converter_1.xci
# IP: The module: 'axis_dwidth_converter_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alex/GitHub/zynq-ip-cores/aes_1.0/src/axis_dwidth_converter_1_1/axis_dwidth_converter_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
