set_property SRC_FILE_INFO {cfile:c:/SHS/Zynq7000AP_SoC_Ethernet_Packet_Redirection_Design/HW/nicap_extend/nicap_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xdc rfile:../nicap_test.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_2/design_1_processing_system7_0_2.xdc id:1 order:EARLY scoped_inst:design_1_wrapper/design_1_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/SHS/Zynq7000AP_SoC_Ethernet_Packet_Redirection_Design/HW/nicap_extend/nicap_test.srcs/constrs_1/new/top_io.xdc rfile:../nicap_test.srcs/constrs_1/new/top_io.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:3 order:LATE scoped_inst:{design_1_wrapper/design_1_i/axi_smc/inst/s00_nodes/s00_ar_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:4 order:LATE scoped_inst:{design_1_wrapper/design_1_i/axi_smc/inst/s00_nodes/s00_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory} unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D16" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C17" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D15" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E16" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C15" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C16" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F15" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A16" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B17" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A17" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B18" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D9" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C6" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P4" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W5" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W4" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C1" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y2" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y4" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V1" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U3" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U4" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T4" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G3" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N1" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L5" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J4" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M3" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K2" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F5" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:721 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {leds_0[0]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {leds_0[1]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {leds_0[2]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {leds_0[3]}]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[31]}]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[24]}]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[8]}]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[1]}]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[20]}]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[21]}]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[27]}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[28]}]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[9]}]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[5]}]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[14]}]
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[29]}]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[30]}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[23]}]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[16]}]
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[25]}]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[4]}]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[12]}]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[22]}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[2]}]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[17]}]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[10]}]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[0]}]
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[3]}]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[13]}]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[18]}]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[6]}]
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[15]}]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[19]}]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[26]}]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[7]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_fifo_data_reg_n_0_[11]}]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_fifo_last_reg_n_0]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_fifo_wr_reg_n_0]
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_sm[1]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_sm[0]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_sm_check_reg_n_0]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_sm_reg_n_0_[0]}]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_sm_reg_n_0_[1]}]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[2]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[15]_i_3_n_0}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[11]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[3]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[4]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[8]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[24]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[17]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[26]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[20]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[25]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[27]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[10]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[5]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[15]_i_2_n_0}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[19]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[1]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[9]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[7]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[31]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[13]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[28]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[30]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[22]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[29]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[23]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[15]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[16]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[21]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[0]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[6]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[12]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[18]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData[14]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[28]}]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[23]}]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[9]}]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[2]}]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[25]}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[16]}]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[27]}]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[20]}]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[8]}]
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[1]}]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[21]}]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[14]}]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[23]}]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[18]}]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[13]}]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[1]}]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[12]}]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[4]}]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[27]}]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[30]}]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[6]}]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[10]}]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[0]}]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[29]}]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[17]}]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[29]}]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[5]}]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[8]}]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[31]}]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[12]}]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[3]}]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[24]}]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[24]}]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[17]}]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[2]}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[10]}]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[19]}]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[6]}]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[9]}]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[3]}]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[13]}]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[26]}]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[22]}]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[26]}]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[16]}]
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[22]}]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[11]}]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[15]}]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[30]}]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[5]}]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[11]}]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[15]}]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[19]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[28]}]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[4]}]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[0]}]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[18]}]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[25]}]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[21]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[31]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[7]}]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_frameData_reg_n_0_[14]}]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[20]}]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_match_reg_reg_n_0_[7]}]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state[1]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state[2]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state[0]_i_1_n_0}]
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/config_state]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state[3]_i_2_n_0}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state_reg_n_0_[3]}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state_reg_n_0_[1]}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/config_state_reg_n_0_[2]}]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/len_to_check_reg_n_0]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/m_axis_tlast]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/m_axis_tvalid]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/m_axis_tready]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/state_reg_n_0_[0]}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/useLcl_0]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[6]}]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[31]}]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[21]}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[13]}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[9]}]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[22]}]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[4]}]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[20]}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[27]}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[26]}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[31]}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[31]}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[21]}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[4]}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[18]}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[0]}]
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[24]}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[12]}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[30]}]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[27]}]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[3]}]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[9]}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[17]}]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[3]}]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[31]}]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[19]}]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[5]}]
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[14]}]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[17]}]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[30]}]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[21]}]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[29]}]
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[13]}]
set_property src_info {type:XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[26]}]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[29]}]
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[16]}]
set_property src_info {type:XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[14]}]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[8]}]
set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[16]}]
set_property src_info {type:XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[13]}]
set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[15]}]
set_property src_info {type:XDC file:2 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[27]}]
set_property src_info {type:XDC file:2 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[14]}]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[21]}]
set_property src_info {type:XDC file:2 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[9]}]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[10]}]
set_property src_info {type:XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[12]}]
set_property src_info {type:XDC file:2 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[30]}]
set_property src_info {type:XDC file:2 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[5]}]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[17]}]
set_property src_info {type:XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[28]}]
set_property src_info {type:XDC file:2 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[16]}]
set_property src_info {type:XDC file:2 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[2]}]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[20]}]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[11]}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[19]}]
set_property src_info {type:XDC file:2 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/m_axis_tready]
set_property src_info {type:XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[26]}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[11]}]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[29]}]
set_property src_info {type:XDC file:2 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[18]}]
set_property src_info {type:XDC file:2 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[7]}]
set_property src_info {type:XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[25]}]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[22]}]
set_property src_info {type:XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[30]}]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[24]}]
set_property src_info {type:XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[12]}]
set_property src_info {type:XDC file:2 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[5]}]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[30]}]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[8]}]
set_property src_info {type:XDC file:2 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[7]}]
set_property src_info {type:XDC file:2 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[29]}]
set_property src_info {type:XDC file:2 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[28]}]
set_property src_info {type:XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[7]}]
set_property src_info {type:XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[20]}]
set_property src_info {type:XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[19]}]
set_property src_info {type:XDC file:2 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[9]}]
set_property src_info {type:XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[10]}]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[9]}]
set_property src_info {type:XDC file:2 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[8]}]
set_property src_info {type:XDC file:2 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/s_axis_tvalid]
set_property src_info {type:XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[26]}]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[4]}]
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/m_axis_tvalid]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[6]}]
set_property src_info {type:XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[21]}]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[11]}]
set_property src_info {type:XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[31]}]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[10]}]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[0]}]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[18]}]
set_property src_info {type:XDC file:2 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[18]}]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[19]}]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[26]}]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[22]}]
set_property src_info {type:XDC file:2 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[11]}]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[22]}]
set_property src_info {type:XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[8]}]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[4]}]
set_property src_info {type:XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[1]}]
set_property src_info {type:XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[20]}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[27]}]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[15]}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[14]}]
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[22]}]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[13]}]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[1]}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[28]}]
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[28]}]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[10]}]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[3]}]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[23]}]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[8]}]
set_property src_info {type:XDC file:2 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[17]}]
set_property src_info {type:XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[18]}]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[24]}]
set_property src_info {type:XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[25]}]
set_property src_info {type:XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[23]}]
set_property src_info {type:XDC file:2 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[0]}]
set_property src_info {type:XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[27]}]
set_property src_info {type:XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[6]}]
set_property src_info {type:XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[1]}]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[25]}]
set_property src_info {type:XDC file:2 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[1]}]
set_property src_info {type:XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[7]}]
set_property src_info {type:XDC file:2 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[15]}]
set_property src_info {type:XDC file:2 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[23]}]
set_property src_info {type:XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[5]}]
set_property src_info {type:XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[15]}]
set_property src_info {type:XDC file:2 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[29]}]
set_property src_info {type:XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[12]}]
set_property src_info {type:XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/s_axis_tdata[25]}]
set_property src_info {type:XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[19]}]
set_property src_info {type:XDC file:2 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[23]}]
set_property src_info {type:XDC file:2 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[11]}]
set_property src_info {type:XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[24]}]
set_property src_info {type:XDC file:2 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[20]}]
set_property src_info {type:XDC file:2 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[3]}]
set_property src_info {type:XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/m_axis_tlast]
set_property src_info {type:XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[0]}]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[23]}]
set_property src_info {type:XDC file:2 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[16]}]
set_property src_info {type:XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[6]}]
set_property src_info {type:XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/m_axis_tdata[2]}]
set_property src_info {type:XDC file:2 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/s_axis_tready]
set_property src_info {type:XDC file:2 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[28]}]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[17]}]
set_property src_info {type:XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets eth_bridge/bit_buffer/s_axis_tlast]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[2]}]
set_property src_info {type:XDC file:2 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[15]}]
set_property src_info {type:XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[10]}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_wr_data_count[14]}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[16]}]
set_property src_info {type:XDC file:2 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[25]}]
set_property src_info {type:XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_data_count[24]}]
set_property src_info {type:XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[2]}]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[12]}]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {eth_bridge/bit_buffer/axis_rd_data_count[13]}]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -hier  -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
